### PR TITLE
Add English template and other minor fixes

### PR DESCRIPTION
**Pull request by Affonso-Gui**

### CODE REVIEW

**Comment by pazeshun** [comment]
@knorth55 Could you review this?

**Comment by knorth55** [comment]
@Affonso-Gui
Do you need japanese abstract in English thesis?
Also, do you need japanese title and japanese name?

**Comment by Affonso-Gui** [comment]
Am confirming that. The title seems to be necessary in both languages but am not sure about the abstract. (The sample provided by the office does include both though)

**Comment by knorth55** [comment]
it seems you don't need japanese abstract, doesn't it?

**Comment by Affonso-Gui** [comment]
@knorth55 Apparently we do need both (in different order), so am leaving this PR as it is

**Comment by knorth55** [comment]
OK i will merge this

**Pull request merged**
